[package]
name = "tauri-plugin-file-actions"
version = "0.1.0"
authors = [ "You" ]
description = "Native iOS preview and sharing of exported comic files"
edition = "2021"
rust-version = "1.71"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-file-actions"

[dependencies]
tauri = { version = "2" }
serde = "1.0"
thiserror = "1.0"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
